version: '3.8'

services:
  app:
    image: shortner:latest
    ports:
      - "5432:5432"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://ukranians.celuobfoolw5.us-east-2.rds.amazonaws.com:5432/ukr
      SPRING_DATASOURCE_USERNAME: social
      SPRING_DATASOURCE_PASSWORD: parac3tam0l
      SPRING_PROFILES_ACTIVE: production
      app.jwtExpirationMs: 86400000
    depends_on:
      - db

  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: goit
      POSTGRES_PASSWORD: password12345
      POSTGRES_DB: projectDb

