CREATE TABLE IF NOT EXISTS USERS (
    id IDENTITY PRIMARY KEY,
    nickName VARCHAR(255) NOT NULL,
    password VARCHAR(1024) NOT NULL
);

CREATE TABLE IF NOT EXISTS URL (
    shortURL VARCHAR(200) PRIMARY KEY,
    longURL VARCHAR(1024) NOT NULL,
    createDate TIMESTAMP(8) NOT NULL,
    clicks VARCHAR(1024) NOT NULL,
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE
);