name: Java CI with Gradle
run-name: ${{ github.actor }} run tests
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set Environment Variables
        run: |
          echo "DB_URL=${{ env.LOCAL_DB_URL }}" >> .env
          echo "DB_USERNAME=${{ env.LOCAL_DB_USERNAME }}" >> .env
          echo "DB_PASSWORD=${{ env.LOCAL_DB_PASSWORD }}" >> .env
          echo "SPRING_PROFILES_ACTIVE=${{ env.SPRING_PROFILES_ACTIVE }}" >> .env
          echo "source .env"

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Gradle
        run: gradle clean test