name: Java CI with Gradle
run-name: ${{ github.actor }} run tests
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

#env:
#  LOCAL_DB_USERNAME: social


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set Environment Variables
        run: |
          echo "DB_URL=${{ env.LOCAL_DB_URL }}" >> .env
          echo "DB_USERNAME=${{ env.LOCAL_DB_USERNAME }}" >> .env
          echo "DB_PASSWORD=${{ env.LOCAL_DB_PASSWORD }}" >> .env
          echo "source .env"
#      -env:
#        DB_URL=jdbc:postgresql://ukranians.celuobfoolw5.us-east-2.rds.amazonaws.com:5432/ukr
#        DB_USERNAME=social
#        DB_PASSWORD=parac3tam0l

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        run: gradle clean test
        env:
          DB_URL: jdbc:postgresql://ukranians.celuobfoolw5.us-east-2.rds.amazonaws.com:5432/ukr
          DB_USERNAME: echo "$LOCAL_DB_USERNAME"
          DB_PASSWORD: parac3tam0l

#          echo "DB_URL=${{ env.LOCAL_DB_URL }}" >> .env
#          echo "DB_USERNAME=${{ env.LOCAL_DB_USERNAME }}" >> .env
#          echo "DB_PASSWORD=${{ env.LOCAL_DB_PASSWORD }}" >> .env